############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
weight = 2
hasChildren = true

[[main]]
parent = "Services"
name = "Diagnostic Audits"
url = "/services/audits"
weight = 1

[[main]]
parent = "Services"
name = "AI Readiness Audit"
url = "/services/ai-readiness-audit"
weight = 2

[[main]]
parent = "Services"
name = "Revenue Analytics"
url = "/services/revenue-analytics"
weight = 3

[[main]]
parent = "Services"
name = "Data Foundation"
url = "/services/data-foundation"
weight = 4

[[main]]
parent = "Services"
name = "Data Activation"
url = "/services/data-activation"
weight = 5

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4


# footer menu
[[footer]]
name = "Services"
url = "/services/revenue-analytics"
weight = 1

[[footer]]
name = "AI Readiness Audit"
url = "/services/ai-readiness-audit"
weight = 2

[[footer]]
name = "About"
url = "/about"
weight = 3

[[footer]]
name = "Blog"
url = "/blog"
weight = 4

[[footer]]
name = "Book a Call"
url = "/contact-us"
weight = 5

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 6

[[footer]]
name = "Terms of Service"
url = "/terms"
weight = 7
